/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment3;

import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Fakhruddin
 */
public class FileIOandArraylist extends javax.swing.JFrame {

    /**
     * Creates new form FileIOandArraylist
     */
    public FileIOandArraylist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namaTF = new javax.swing.JTextField();
        umurTF = new javax.swing.JTextField();
        telefonTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        surahCB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTP = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PENDAFTARAN PELAJAR");

        jLabel1.setText("Nama :");

        jLabel2.setText("Umur :");

        jLabel3.setText("No.Telefon :");

        telefonTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonTFActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        surahCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--- Sila Pilih Satu ---]", "Al-Fatihah", "An-Nas", "Al-Falaq", "Al-Ikhlas" }));
        surahCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surahCBActionPerformed(evt);
            }
        });

        jLabel4.setText("Surah :");

        jScrollPane1.setViewportView(outputTP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(31, 31, 31)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(umurTF)
                            .addComponent(namaTF)
                            .addComponent(surahCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telefonTF))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(umurTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(telefonTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surahCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nama = namaTF.getText();
        String umur = umurTF.getText();
        String telefon = telefonTF.getText();
        int surah = surahCB.getSelectedIndex();

        try{
           FileWriter Writer = new FileWriter ("NAMA PESERTA.txt",true);
           Writer.write("  "+nama+"  "+umur+"  "+telefon+"  "+surah); 
           Writer.write(System.getProperty("line.separator"));
           Writer.close();
           JOptionPane.showMessageDialog(null, "BERJAYA!");
           setVisible(true);
           new FileIOandArraylist().setVisible(false);
           
        }catch(Exception e){
           JOptionPane.showMessageDialog(null, "GAGAL!");
            
        }
        
        
    outputTP.setText("NAMA PESERTA : "+namaTF.getText());
    outputTP.setText("UMUR : "+namaTF.getText());
    outputTP.setText("TELEFON NO. : "+namaTF.getText());
     if(surahCB.getSelectedIndex()==0){
        JOptionPane.showMessageDialog(null, "SILA PILIH SURAH YANG DIINGINKAN!");
    }else if(surahCB.getSelectedIndex()==1){
            outputTP.setText("NAMA PESERTA : "+namaTF.getText()
                    +"\nUMUR : "+umurTF.getText()
                    +"\nTELEFON NO. : "+telefonTF.getText()
                    +"\nSurah Yang Anda Pilih Adalah : Al-Fatihah"
				+"\nYuran dikenakan : rm20");
    }else if(surahCB.getSelectedIndex()==2){
        outputTP.setText("NAMA PESERTA : "+namaTF.getText()
                    +"\nUMUR : "+umurTF.getText()
                    +"\nTELEFON NO. : "+telefonTF.getText()
                    +"\nSurah Yang Anda Pilih Adalah : An-Nas"
				+"\nYuran dikenakan : rm30");
    }else if(surahCB.getSelectedIndex()==3){
        outputTP.setText("NAMA PESERTA : "+namaTF.getText()
                    +"\nUMUR : "+umurTF.getText()
                    +"\nTELEFON NO. : "+telefonTF.getText()
                    +"\nSurah Yang Anda Pilih Adalah : Al-Falaq"
				+"\nYuran dikenakan : rm40");
    }else if(surahCB.getSelectedIndex()==4){
        outputTP.setText("NAMA PESERTA : "+namaTF.getText()
                    +"\nUMUR : "+umurTF.getText()
                    +"\nTELEFON NO. : "+telefonTF.getText()
                    +"\nSurah Yang Anda Pilih Adalah : Al-Ikhlas"
				+"\nYuran dikenakan : rm50");
    }else{
        JOptionPane.showMessageDialog(null, "SILA PILIH SURAH YANG DIINGINKAN!");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        namaTF.setText("");
        umurTF.setText("");
        telefonTF.setText("");
        outputTP.setText("");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void telefonTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonTFActionPerformed

    private void surahCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surahCBActionPerformed
        // TODO add your handling code here:
        //String selectedValue = surahCB.getSelectedItem().toString();
        //outputTF.setText(selectedValue);
        
    }//GEN-LAST:event_surahCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileIOandArraylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileIOandArraylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileIOandArraylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileIOandArraylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileIOandArraylist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namaTF;
    private javax.swing.JTextPane outputTP;
    private javax.swing.JComboBox<String> surahCB;
    private javax.swing.JTextField telefonTF;
    private javax.swing.JTextField umurTF;
    // End of variables declaration//GEN-END:variables
}
